# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yFAFofmFkpRAomXSJpQCvuqwIl3ZbNV
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/placement.csv')

df.head()

"""df.info()

"""

df=df.iloc[:,1:]

df.head()

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])
#

x=df.iloc[:,0:2]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.1)
# xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=2)

from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()

X_train

Y_train

#Model training
clf.fit(X_train,Y_train)

clf.predict(X_test)

Y_pred=Y_test

from sklearn.metrics import accuracy_score

accuracy_score(Y_test,Y_pred)

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X_train, Y_train.values, clf=clf, legend=2)

import pickle

pickle.dump(clf,open('model.pkl','wb'))